a=input('enter a first number:-')
b=input('enter a second number:-')
print('your addition is')
print(a+b)
print('your subtraction is')
print(a-b)
print('your multplication is')
print(a*b)
print('your divison is ')
print(a/b)
